#!/usr/bin/env bash
# PreToolUse (Write|Edit) hook: block edits to files that must never be hand-edited
# or that enforce the harness's own safety boundaries.
#
# File-safety hook: fails CLOSED (deny) if python3 is missing — a safety hook that
# can't verify safety refuses rather than silently allowing.
set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Caller env wins over harness.env (deterministic fixtures); harness.env wins over defaults.
_PRE_LF="${LOCKFILES:-}"
[ -f "$PROJECT_ROOT/.claude/harness.env" ] && . "$PROJECT_ROOT/.claude/harness.env"
LOCKFILES="${_PRE_LF:-${LOCKFILES:-package-lock.json yarn.lock pnpm-lock.yaml Cargo.lock poetry.lock uv.lock Gemfile.lock composer.lock go.sum}}"

INPUT="$(cat)"

deny() {
  python3 -c "
import json, sys
print(json.dumps({'hookSpecificOutput': {'hookEventName': 'PreToolUse', 'permissionDecision': 'deny', 'permissionDecisionReason': sys.argv[1]}}))
" "$1" 2>/dev/null || echo "BLOCKED: $1" >&2
  exit 2
}

if ! command -v python3 >/dev/null 2>&1; then
  deny "protect-files.sh cannot verify safety without python3 — failing closed. Install python3 or review manually."
fi

FILE_PATH="$(python3 -c "import json,sys; d=json.loads(sys.argv[1]); print(d.get('tool_input',{}).get('file_path',''))" "$INPUT" 2>/dev/null || echo "")"

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

base="$(basename "$FILE_PATH")"
basename_lc="$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]')"
path_lc="$(printf '%s' "$FILE_PATH" | tr '[:upper:]' '[:lower:]')"

# Lockfiles: never hand-edited — regenerate via the package manager.
for lock in $LOCKFILES; do
  lock_lc="$(printf '%s' "$lock" | tr '[:upper:]' '[:lower:]')"
  if [[ "$basename_lc" == "$lock_lc" ]]; then
    deny "Cannot hand-edit $base — lockfiles are regenerated by the package manager, never edited. See .claude/rules/safety.md."
  fi
done

# Secret-shaped files.
case "$basename_lc" in
  .env|.env.*|*.pem|*.key|id_rsa|id_ed25519|credentials.json)
    deny "Cannot write to $FILE_PATH — looks like a secret/credential file."
    ;;
esac

# Self-protecting paths: the hooks that enforce these boundaries can't be edited
# away through the same mechanism they constrain.
case "$path_lc" in
  */.git/*)
    deny "Cannot write inside .git/ directly."
    ;;
  */.claude/hooks/*)
    deny "Cannot edit hook scripts via Write/Edit — these enforce this project's safety boundaries. If a hook is genuinely wrong, ask the user to review and edit it directly outside the agentic loop."
    ;;
esac

# settings.json: warn loudly, don't block.
case "$path_lc" in
  */.claude/settings.json)
    python3 -c "
import json
print(json.dumps({'hookSpecificOutput': {'hookEventName': 'PreToolUse', 'additionalContext': 'Reminder: editing .claude/settings.json changes hook/permission wiring for this whole project. Double-check the change is intentional.'}}))
"
    ;;
esac

exit 0
